/*Loon tabelid*/

CREATE TABLE Haldurid (
Id INTEGER NOT NULL DEFAULT
AUTOINCREMENT PRIMARY KEY,
Eesnimi VARCHAR(50) NOT NULL,
Perenimi VARCHAR(30) NOT NULL,
);

CREATE TABLE Kliendid (
Id INTEGER NOT NULL DEFAULT AUTOINCREMENT PRIMARY KEY,
Nimi VARCHAR(50),
Reg_nr INTEGER,
Kliendi_nr INTEGER,
Limiidi_kinnituse_kp DATE,
Haldur INTEGER,
Kes_on_ema INTEGER,
);

CREATE TABLE Monitooringud (
Id INTEGER NOT NULL DEFAULT
AUTOINCREMENT PRIMARY KEY,
Tyyp integer NOT NULL,
Klient integer NOT NULL,
Teostaja integer NOT NULL,
Eelmise_mon_kp DATE,
Jargmise_mon_kp DATE
);

CREATE TABLE Tyybid (
Id INTEGER NOT NULL DEFAULT
AUTOINCREMENT PRIMARY KEY,
nimetus VARCHAR(255) NOT NULL,
);
